GET http://localhost:6678/api/user/login?id=1
Content-Type: application/json

###

POST http://localhost:6678/api/admin/schedule-draft
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzEyNzQyNzYwLCJleHAiOjE3MTI3NDI4MzB9.6eqEFVGHPRS6hvtnBUpjESTCdfqyeh90E3MTb549hXExwER6RAhImDGBMic7NAHA


{
  "dateOfSchedule": "2024-03-01T00:00Z",
  "programs": [
    {
      "startTime": "2024-03-01T00:00Z",
      "endTime": "2024-03-01T01:00Z",
      "name": "Vesti"
    },
    {
      "startTime": "2024-03-01T01:00Z",
      "endTime": "2024-03-01T02:00Z",
      "name": "Dom 2"
    }
  ]
}

###
PATCH http://localhost:6678/api/admin/schedule-draft
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzEyNzQyNzYwLCJleHAiOjE3MTI3NDI4MzB9.6eqEFVGHPRS6hvtnBUpjESTCdfqyeh90E3MTb549hXExwER6RAhImDGBMic7NAHA


{
  "scheduleDraftId": 2,
  "status": "CONFIRMED"
}

###
GET http://localhost:6678/api/admin/schedule-draft


###
GET http://localhost:6678/api/user/schedule?datetime=2024-03-01T01:00Z
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzEyNzQyNTg5LCJleHAiOjE3MTI3NDI2NTl9.jcJ03PPWL-dskcHM1EQhjq_L0lSMxfcV4oFTQdLkhirrIcaThT0lc5_J9_gtpcVB
