openapi: 3.0.3
info:
  title: Schedule service
  version: 1.0.0
servers:
  - url: http://localhost:6678/api/user
    description: Development server
tags:
  - name: util
  - name: program-schedule
paths:
  /ping:
    get:
      operationId: ping
      tags:
        - util
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './common_api.yaml#/components/schemas/pingResponse'
  /schedule:
    get:
      operationId: getScheduleForDay
      tags:
        - program-schedule
      parameters:
        - in: query
          required: true
          name: datetime
          schema:
            type: string
            format: date-time
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scheduleResponse'
        500:
          description: Internal error
          content:
            application/json:
              schema:
                $ref: './common_api.yaml#/components/schemas/errorResponse'

components:
  schemas:
    pingResponse:
      type: object
      properties:
        pong:
          type: string

    program:
      type: object
      required:
        - startTime
        - endTime
        - name
      properties:
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        name:
          type: string

    scheduleResponse:
      type: array
      items:
        $ref: './common_api.yaml#/components/schemas/program'

    errorResponse:
      type: object
      properties:
        reason:
          type: string