openapi: 3.0.3
info:
  title: Schedule service
  version: 1.0.0
servers:
  - url: http://localhost:6678/api/user
    description: Development server
tags:
  - name: util
paths:
  /ping:
    get:
      operationId: ping
      tags:
        - util
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pingResponse'


components:
  schemas:
    pingResponse:
      type: object
      properties:
        pong:
          type: string
